import requests
from urllib.parse import urlparse, parse_qs
import os

# Bước 1: Tiền xử lý
def preprocess_urls(urls):
    # Loại bỏ trùng lặp
    unique_urls = list(set(urls))
    # Sắp xếp theo tham số &p
    sorted_urls = sorted(unique_urls, key=lambda url: int(parse_qs(urlparse(url).query)['p'][0]))
    print(f"Số lượng URL sau khi xử lý: {len(sorted_urls)}")
    return sorted_urls

# Bước 2: Tải ảnh
def download_images(urls, output_folder="downloaded_images"):
    os.makedirs(output_folder, exist_ok=True)
    for url in urls:
        try:
            page_num = parse_qs(urlparse(url).query)['p'][0]
            response = requests.get(url)
            response.raise_for_status()
            image_path = os.path.join(output_folder, f"page_{page_num}.jpg")
            with open(image_path, 'wb') as f:
                f.write(response.content)
            print(f"✅ Đã tải: {image_path}")
        except requests.RequestException as e:
            print(f"❌ Lỗi khi tải {url}: {e}")

# Danh sách URL đầu vào
urls = [
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=1&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=2&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=3&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=4&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=5&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=6&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=7&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=8&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=9&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=10&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=7&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=11&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=12&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=13&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=14&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=15&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=16&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=17&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=18&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=19&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=20&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=21&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=22&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=23&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=20&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=19&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=18&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=17&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=16&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=15&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=14&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=13&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=12&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=11&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=10&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=9&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=8&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=7&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=6&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=5&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=4&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=4&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=5&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=6&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=7&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=8&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=9&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=10&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=11&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=12&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=13&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=14&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=15&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=16&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=115&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=116&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=117&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=142&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=143&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=144&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=152&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=153&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=154&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=155&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=156&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=157&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=158&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=159&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=160&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=161&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=162&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=163&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=164&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=168&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=169&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=170&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=173&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=174&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=175&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=176&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=177&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=178&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=179&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=180&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=181&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=182&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=183&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=184&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=185&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=186&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=187&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=188&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=189&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=190&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=191&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=192&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=193&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=194&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=188&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=187&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=186&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=185&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=184&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=183&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=182&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=181&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=180&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=179&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=178&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=177&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=176&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=175&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=174&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=173&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=172&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=171&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=170&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=169&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=168&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=167&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=166&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=165&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=164&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=163&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=162&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=161&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=160&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=159&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=158&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=157&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=156&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=155&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=154&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=153&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=152&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=151&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=150&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=149&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=148&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=147&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=146&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=145&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=144&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=143&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=142&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=141&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=140&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=139&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=138&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=137&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=136&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=135&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=134&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=133&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=132&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=131&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=130&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=129&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=128&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=127&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=126&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=120&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=121&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=122&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=119&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=118&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=117&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=116&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=115&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=114&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=113&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=112&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=111&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=109&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=110&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=108&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=106&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=107&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=104&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=105&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=102&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=103&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=96&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=97&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=98&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=93&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=94&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=95&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=90&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=91&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=92&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=88&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=89&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=86&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=87&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=85&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=84&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=83&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=82&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=81&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=78&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=79&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=80&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=77&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=76&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=75&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=74&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=73&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=72&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=71&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=70&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=69&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=68&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=67&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=66&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=65&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=64&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=63&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=62&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=59&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D",
    "https://sachbaovn.vn/readonline/page.ashx?id=146&p=58&z=7&sig=seqfOaBRdUL4pMNpPgetTQ%3D%3D"
]

# Thực thi chương trình
processed_urls = preprocess_urls(urls)
download_images(processed_urls)
